import React from "react";
import { useNavigate } from "react-router-dom";
import { FaArrowLeft } from "react-icons/fa";

const TermsAndConditions = () => {
  const navigate = useNavigate();
  return (
    <div className="bg-white px-6 py-10 max-w-4xl mx-auto text-gray-800">
      <div className="max-w-7xl mx-auto flex items-center">
        <button
          onClick={() => navigate("/")}
          className="flex items-center gap-2 text-gray-700 hover:text-orange-600 transition-colors font-medium"
        >
          <FaArrowLeft className="text-lg" />
          <span>Back</span>
        </button>
      </div>
      <h1 className="text-3xl font-bold mb-6 text-center">
        Terms & Conditions
      </h1>
      <p className="mb-4 text-sm">
        This document is an electronic record in terms of the Information
        Technology Act, 2000 and rules thereunder as applicable and the amended
        provisions pertaining to electronic records in various statutes as
        amended by the Information Technology Act, 2000. This electronic record
        is generated by a computer system and does not require any physical or
        digital signatures.
      </p>
      <p className="mb-4 text-sm">
        This document is published in accordance with the provisions of Rule 3
        (1) of the Information Technology (Intermediaries guidelines) Rules,
        2011 that require publishing the rules and regulations, privacy policy
        and Terms of Use for access or usage of domain name
        <strong> https://willovateresto.com </strong> (“Website”), including the
        related mobile site and mobile application (hereinafter referred to as
        “Platform”).
      </p>
      <p className="mb-4 text-sm">
        The Platform is owned by <strong>Willovate Private Limited</strong>, a
        company incorporated under the Companies Act, 2013 with its registered
        office at{" "}
        <strong>
          [305,at Mundipar, Lakhni, Bhandara, Lakhni, Maharashtra, India, 441804
          ]
        </strong>{" "}
        (hereinafter referred to as "Platform Owner", "we", "us", "our").
      </p>
      <h2 className="text-xl font-semibold mt-8 mb-2">
        1. Acceptance of Terms
      </h2>
      <p className="mb-4 text-sm">
        By accessing or using the Platform, you agree to be bound by these
        Terms. These Terms constitute a binding agreement between you and
        Willovate Private Limited.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">
        2. User Responsibilities
      </h2>
      <p className="mb-4 text-sm">
        You agree to provide accurate, current, and complete information and
        maintain the security of your account. You are responsible for all
        activities that occur under your account.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">3. Use of Services</h2>
      <p className="mb-4 text-sm">
        You agree to use our Platform and services only for lawful purposes and
        in accordance with these Terms. Unauthorized use may result in legal
        action.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">4. Payment & Charges</h2>
      <p className="mb-4 text-sm">
        You agree to pay all applicable charges for services. Transactions are
        governed by our policies and applicable Indian law.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">
        5. Intellectual Property
      </h2>
      <p className="mb-4 text-sm">
        All content on the Platform including logos, designs, and software are
        our property. You may not reproduce or use our intellectual property
        without prior written permission.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">6. Third-Party Links</h2>
      <p className="mb-4 text-sm">
        The Platform may contain links to third-party sites. We are not
        responsible for the content or privacy practices of those sites.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">7. Indemnification</h2>
      <p className="mb-4 text-sm">
        You agree to indemnify and hold harmless Willovate Private Limited and
        its affiliates against any losses arising out of your use of the
        Platform or violation of these Terms.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">
        8. Limitation of Liability
      </h2>
      <p className="mb-4 text-sm">
        We are not liable for any indirect, incidental, or consequential
        damages. Our maximum liability is limited to ₹100 or the amount paid by
        you, whichever is less.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">9. Jurisdiction</h2>
      <p className="mb-4 text-sm">
        These Terms are governed by the laws of India. Any disputes shall be
        subject to the exclusive jurisdiction of courts located in
        <strong> [Nagpur, Maharastra] </strong>.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">10. Contact Us</h2>
      <p className="mb-4 text-sm">
        For any queries or complaints, you may contact us at:
        <br />
        📧 admin@willovate.com
      </p>
    </div>
  );
};

export default TermsAndConditions;
